name: Make ZIP

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create zip file
        run: |
          tag_name=$(git describe --tags --abbrev=0)
          zip -r "directorist-wpml-integration.${tag_name}.zip" directorist-wpml-integration

      - name: Upload zip file as a release asset
        uses: softprops/action-gh-release@v1
        with:
          files: directorist-wpml-integration*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
